Replace bash with sh due to official small .NET ASP.NET runtime image.

diff --git a/.github/workflows/master_datastructviz.yml b/.github/workflows/master_datastructviz.yml
--- a/.github/workflows/master_datastructviz.yml
+++ b/.github/workflows/master_datastructviz.yml
@@ -26,11 +26,12 @@ jobs:
 
       - name: Check if ICU is installed inside container (safe way)
         run: |
-            docker run --rm --entrypoint bash abalan95/blazorapp:latest2 -c "ldconfig -p | grep libicu || echo 'ICU NOT FOUND'"
+            docker run --rm --entrypoint sh abalan95/blazorapp:latest2 -c "ldconfig -p | grep libicu || echo 'ICU NOT FOUND'"
 
       - name: Push Docker image to Docker Hub
         run: |
             docker push abalan95/blazorapp:latest2
+
 
 
   deploy-to-vps:
